### ISSUE TITLE
[Bug]: Minecolonies 

### ISSUE THREAD

**Issue by mogcid** [Iskariot53/MinecoloniesCreateandConquer#2]
### Possible Fixes

Yes

### Modpack Version

b0.0.8

### What happened?

Hello several problems:
The Forester's Hut does not work, message This block is missing respective building, try restart or loading a backup.

Why install the Builder Wand mod when there is a simple and effective mod called Construction Wand?

Several quests do not work like the torch master and a colleague the minecolonies builder

A little suggestion more craft mods please I hate that when a modpack is made it makes craft mods to add difficulty to the modpack yes but no addition of craft please
Thanks

**Comment by mogcid** [comment]
For minecolonies it is apparently necessary because it is written in the mod Tweak of minecolonies to use the mod Target version
Minecolonies 1.1.694
Structuriez 1.0.740
Multi piston 1.2.43
Domum Or... 1.0.186
BlockUI 1.0.156 

Im test today good night

**Comment by Iskariot53** [comment]
We are aware of the issue with the forester's hut and currently working on switching to a more stable, recent version. So this will be remedied in the next update which won't be long.

The wands mod is effectively the same and given the caps in place effectively a matter of opinion/choice.

the torch master quest works, it is a submissions quest, so you must submit the 3 torches to complete. This will be better explained in the quest details, thank you for bringing it up as it has confused a few people so it is another thing that will be changed in the next update. I'm not sure about what other quests you may be having issues with but as a side note, we are currently trying to run down something causing a syncing issue with quests, so if one is not acknowledging, relogging will help for now.

I'm not exactly sure what your last comment about "crafts mods" implies, but if you can elaborate, we would be more than happy to take any suggestions into consideration.

**Comment by Iskariot53** [comment]
> For minecolonies it is apparently necessary because it is written in the mod Tweak of minecolonies to use the mod Target version Minecolonies 1.1.694 Structuriez 1.0.740 Multi piston 1.2.43 Domum Or... 1.0.186 BlockUI 1.0.156
> 
> Im test today good night

I don't think this is the actual cause of the issue but will look into this, thank you for your feedback.

**Comment by mogcid** [comment]
I didn't understand your story about 3 torches, why 3 torches again? in the mod config and change that

**Comment by mogcid** [comment]
doesn't work no matter what and I didn't understand anything more lol month I put the mega torch down, broke it, picked it up 3 times and I didn't get a mega torch I think you're not talking about the same thing the first minecolonies quest, plus the quest The heartbeat of every community doesn't work I had the advent and nothing no quest to validate. The ftb quest mod itself in this version has crazy latency I noticed that, there are 2 of us players who haven't had the quest

**Comment by Iskariot53** [comment]
> doesn't work no matter what and I didn't understand anything more lol month I put the mega torch down, broke it, picked it up 3 times and I didn't get a mega torch I think you're not talking about the same thing the first minecolonies quest, plus the quest The heartbeat of every community doesn't work I had the advent and nothing no quest to validate. The ftb quest mod itself in this version has crazy latency I noticed that, there are 2 of us players who haven't had the quest

The quest for the mega torch works and works as intended. Get 3 torchs in inventory. CLick torch icon in the quest. Click submit.

the heartbeat of every community may be a legitimate issue though, since it is advancement based. It works in testing, but we can look into changing the quest requirements to hut blocks to better avoid this.

**Comment by mogcid** [comment]
For info I play on a server and this morning the server stopped, it restarted and I joined the server.... and crash, the Create Mission mod crashes... I'll spare you the details

**Comment by mogcid** [comment]
discord is not reachable via the link

**Comment by mogcid** [comment]
I said it's because of this mod, sorry I don't have a log because I did my own analysis I deleted the mod and redid a world backup because the word was corrupted... minecolonies broken...

**Comment by mogcid** [comment]
you don't trust me i made my own are you stupid or what have you tested this modapck on server no?, there are no server files so no

**Comment by Iskariot53** [comment]
> you don't trust me i made my own are you stupid or what have you tested this modapck on server no?, there are no server files so no

No, I don't believe you if i'm to be honest. For good reason. Read my previous comments and you can answer this for yourself. It is pretty plainly pointed out.

I find it hilarious you have the audacity to call someone else stupid though. The best suggestion i can give you at this point is: Play something else and stop bothering me or adjust your attitude.

**Comment by mogcid** [comment]
are you serious there I mentioned just for information and you are giving me your crisis because I did my own analysis and I communicated simply to help you develop this modpack are you serious there not to believe me come on my stream and you will not see for yourself I am just French lol
