### ISSUE TITLE
[Bug]: link discord

### ISSUE THREAD

**Issue by mogcid** [Iskariot53/MinecoloniesCreateandConquer#4]
### Possible Fixes

Yes

### Modpack Version

b0.0.9

### What happened?

link discord not good
![Capture d’écran 2024-11-22 103501](https://github.com/user-attachments/assets/f9819091-c9e3-49b4-9166-446e7d609b2e)

**Comment by Iskariot53** [comment]
Which link are you trying to use? Screenshot gives no information.
